services:
  mysql:
    image: mysql:8.0
    container_name: "book-portal-db"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bookportal
    volumes:
      - db-data:/var/lib/mysql

  book-portal-be:
    build: ./book-portal-be
    container_name: "book-portal-be"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookportal?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  book-portal-fe:
    build: ./book-portal-fe
    container_name: "book-portal-fe"
    depends_on:
      - book-portal-be

  proxy:
    build: ./nginx
    container_name: "book-portal-proxy"
    restart: always
    ports:
      - "80:80"

volumes:
  db-data:
